### PR TITLE
Deploy test environment from main branch

### PR DESCRIPTION
**Pull request by johnbradley**
Adds configuration to deploy changes from main to our test environment. Currently the test environment serves https://www.datadrivenhypothesis.org/. Next I will add a prod environment and setup a method to scale down the test environment.

### CODE REVIEW

**Comment by johnbradley** [comment]
I'm having random deployment failures due to docker/github pull limits. So I'm going to add changes to authenticate with these two services with credentials to fix this.

**Comment by johnbradley** [comment]
I added a secret in Secret Manager with docker credentials and used this in the pipeline. 
The build seems reliable now, but will revisit if I see any issues with GitHub in the future.

**Comment by johnbradley** [comment]
How to view the pipeline in the AWS console:
## 1. Search for "Code Pipeline" click CodePipeline
Screen Shot 2022-12-16 at 9 45 55 AM

## 2. Select a pipeline

Screen Shot 2022-12-16 at 9 46 05 AM

## 3. View high level details of the build
Screen Shot 2022-12-16 at 9 46 25 AM

## 4. Click "Details" under Build to view logs
Screen Shot 2022-12-16 at 9 48 16 AM

## 5. Scroll down to see the logs
Screen Shot 2022-12-16 at 9 49 15 AM

**Review by matthewhirschey — APPROVED** [review]
LGTM!

**Pull request merged**
